### ISSUE TITLE
cd PWD et OLDPWD

### ISSUE THREAD

**Issue by ThomasCharuel** [ThomasCharuel/minishell#13]

**Comment by ThomasCharuel** [comment]
cd -

**Comment by TulipeSoyeuse** [comment]
Techniquement oldpwd est générer par bash pas directement par cd ( puisque absent de la doc ) donc on devrait pas avoir à le gérer

**Comment by ThomasCharuel** [comment]
je suis 100% d'accord, mais on m'en a parle plusieurs fois

Je close l'issue ca degage
